#!/usr/bin/env bash

. /etc/container_environment.sh

function on_exit {
    ${HADOOP_PREFIX}/sbin/stop-yarn.sh
    exit 0
}
trap on_exit INT TERM HUP

# start ssh service
sv start sshd || exit 1
# wait for ssh service ready
my_tcp_wait '127.0.0.1' 22
# Wait for Kerberos service
my_service "wait" ${KRB_SERVICE_NAME}

su ${HADOOP_YARN_USER} --preserve-environment -c ${HADOOP_PREFIX}/sbin/start-yarn.sh

sleep infinity &
wait $!
