#!/usr/bin/env bash

. /etc/container_environment.sh

function on_exit {
    ${HADOOP_PREFIX}/sbin/stop-yarn.sh
    exit 0
}
trap on_exit INT TERM HUP

# this and wait for SSH server up and running
sv start sshd || exit 1
while true; do
    dockerize -wait tcp://localhost:22 -timeout 2s
    if [[ $? -eq 0 ]]; then
        break
    fi
done

# Wait for Kerberos service
my_service "wait" ${KRB_SERVICE_NAME}

su ${HADOOP_YARN_USER} --preserve-environment -c ${HADOOP_PREFIX}/sbin/start-yarn.sh

sleep infinity &
wait $!
