#!/usr/bin/env bash

. /etc/container_environment.sh

function on_exit {
    ${HADOOP_PREFIX}/sbin/stop-dfs.sh
    exit 0
}
trap on_exit INT TERM HUP

# this and wait for SSH server up and running
sv start sshd || exit 1
while true; do
    dockerize -wait tcp://localhost:22 -timeout 2s
    if [[ $? -eq 0 ]]; then
        break
    fi
done

# Wait for Kerberos service
my_service "wait" ${KRB_SERVICE_NAME}

su ${HADOOP_HDFS_USER} --preserve-environment -c "${HADOOP_PREFIX}/sbin/start-dfs.sh"
if [ -n "${HADOOP_SECURE_DN_USER}" ]; then
    ${HADOOP_PREFIX}/sbin/start-secure-dns.sh
fi

sleep infinity &
wait $1
